# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20170731_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=2000)),
                ('recieved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('users_notify', models.ManyToManyField(to='users.CAProfile')),
            ],
        ),
    ]
