# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caprofile',
            name='fb_link',
        ),
        migrations.AddField(
            model_name='kyprofile',
            name='profile_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='kyprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
