# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='ca_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
