# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170731_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='regs',
            field=models.ManyToManyField(blank=True, null=True, related_name='regs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='whatsapp_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
