# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170815_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='caprofile',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
