# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171017_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyprofile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://storage.forums.net/6479407/images/vagmAzMznjBJGQf_sumV.png', null=True),
        ),
    ]
