# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171017_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventsList', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='kyprofile',
            name='eventsList',
            field=models.TextField(null=True),
        ),
    ]
