# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171026_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyprofile',
            name='eventsList',
        ),
    ]
