# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_kyprofile_eventslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyprofile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
