# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_kyprofile_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyprofile',
            name='payment_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
