# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_kyprofile_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyprofile',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
