# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171205_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyprofile',
            name='paid_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
