# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('contingentId', models.AutoField(primary_key=True, serialize=False)),
                ('contingentLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='con_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50)),
                ('eventDetails', models.TextField()),
                ('maxMembers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minMembers', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentEvent',
            fields=[
                ('parentEventId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamName', models.CharField(blank=True, max_length=250, null=True)),
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('teamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamLeader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='parentEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ParentEvent'),
        ),
    ]
