# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingent',
            name='contingentLeader',
        ),
        migrations.RemoveField(
            model_name='contingent',
            name='members',
        ),
        migrations.DeleteModel(
            name='Contingent',
        ),
    ]
