# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='users_notify',
            new_name='users',
        ),
    ]
