# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
