# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0004_auto_20170813_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
