# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_caprofile_reason'),
        ('etc', '0005_post_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='main_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='read_date',
        ),
        migrations.AddField(
            model_name='notifications',
            name='mark_read',
            field=models.ManyToManyField(related_name='mark_read', to='users.CAProfile'),
        ),
    ]
