# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0007_auto_20170923_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='mark_read', to='users.CAProfile'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.CAProfile'),
        ),
    ]
