# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_caprofile_reason'),
        ('etc', '0008_auto_20170923_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('designation', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CAProfile')),
            ],
        ),
    ]
