# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171017_1627'),
        ('etc', '0009_publicrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_points', models.IntegerField(default=0)),
                ('fb_points', models.IntegerField(default=0)),
                ('extra_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CAProfile')),
            ],
        ),
    ]
