# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0011_point_reg_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='payment_points',
            field=models.IntegerField(default=0),
        ),
    ]
