# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0012_point_payment_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('img_url', models.URLField(blank=True, null=True)),
                ('redirect_link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default='2018-01-08T10:16:55.647895')),
            ],
        ),
    ]
